/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 AboutMe.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function AboutMeText(props) {
  const { nodes, materials } = useGLTF('/AboutMe.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-6, 1, -16]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.02}>
        <group position={[0, 0, 105.609]}>
          <mesh geometry={nodes['3D_Text_-_Letter'].geometry} material={materials.Afternoon} position={[-103.272, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_24'].geometry} material={materials.Afternoon} position={[73.434, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_31'].geometry} material={materials.Afternoon} position={[-83.186, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_107'].geometry} material={materials.Afternoon} position={[-103.272, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_116'].geometry} material={materials.Afternoon} position={[-32.194, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_120'].geometry} material={materials.Afternoon} position={[-6.733, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_133'].geometry} material={materials.Afternoon} position={[94.414, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_141'].geometry} material={materials.Afternoon} position={[-53.002, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_1'].geometry} material={materials.Afternoon} position={[-96.773, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_12'].geometry} material={materials.Afternoon} position={[-18.819, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_21'].geometry} material={materials.Afternoon} position={[54.527, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_41'].geometry} material={materials.Afternoon} position={[-3.44, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_89'].geometry} material={materials.Afternoon} position={[7.221, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_105'].geometry} material={materials.Afternoon} position={[111.407, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_108'].geometry} material={materials.Afternoon} position={[-96.773, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_126'].geometry} material={materials.Afternoon} position={[43.687, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_2'].geometry} material={materials.Afternoon} position={[-88.818, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_43'].geometry} material={materials.Afternoon} position={[12.624, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_58'].geometry} material={materials.Afternoon} position={[-42.221, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_99'].geometry} material={materials.Afternoon} position={[70.862, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_109'].geometry} material={materials.Afternoon} position={[-88.818, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_140'].geometry} material={materials.Afternoon} position={[-68.688, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_3'].geometry} material={materials.Afternoon} position={[-76.353, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_19'].geometry} material={materials.Afternoon} position={[41.502, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_42'].geometry} material={materials.Afternoon} position={[4.515, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_110'].geometry} material={materials.Afternoon} position={[-76.353, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_4'].geometry} material={materials.Afternoon} position={[-68.244, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_72'].geometry} material={materials.Afternoon} position={[61.587, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_100'].geometry} material={materials.Afternoon} position={[83.327, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_111'].geometry} material={materials.Afternoon} position={[-68.244, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_142'].geometry} material={materials.Afternoon} position={[-46.503, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_152'].geometry} material={materials.Afternoon} position={[18.006, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_5'].geometry} material={materials.Afternoon} position={[-60.219, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_25'].geometry} material={materials.Afternoon} position={[79.933, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_29'].geometry} material={materials.Afternoon} position={[-96.351, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_46'].geometry} material={materials.Afternoon} position={[40.607, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_61'].geometry} material={materials.Afternoon} position={[-15.064, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_66'].geometry} material={materials.Afternoon} position={[17.232, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_77'].geometry} material={materials.Afternoon} position={[-87.987, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_79'].geometry} material={materials.Afternoon} position={[-71.111, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_103'].geometry} material={materials.Afternoon} position={[102.332, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_112'].geometry} material={materials.Afternoon} position={[-60.219, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_123'].geometry} material={materials.Afternoon} position={[18.015, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_147'].geometry} material={materials.Afternoon} position={[-13.128, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_151'].geometry} material={materials.Afternoon} position={[12.375, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_6'].geometry} material={materials.Afternoon} position={[-54.589, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_17'].geometry} material={materials.Afternoon} position={[22.791, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_23'].geometry} material={materials.Afternoon} position={[65.941, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_34'].geometry} material={materials.Afternoon} position={[-55.176, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_37'].geometry} material={materials.Afternoon} position={[-28.355, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_39'].geometry} material={materials.Afternoon} position={[-14.378, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_44'].geometry} material={materials.Afternoon} position={[25.089, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_62'].geometry} material={materials.Afternoon} position={[-9.434, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_64'].geometry} material={materials.Afternoon} position={[2.975, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_67'].geometry} material={materials.Afternoon} position={[22.862, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_82'].geometry} material={materials.Afternoon} position={[-52.539, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_91'].geometry} material={materials.Afternoon} position={[23.174, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_113'].geometry} material={materials.Afternoon} position={[-54.589, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_118'].geometry} material={materials.Afternoon} position={[-22.251, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_121'].geometry} material={materials.Afternoon} position={[-0.234, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_125'].geometry} material={materials.Afternoon} position={[36.194, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_132'].geometry} material={materials.Afternoon} position={[86.921, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_145'].geometry} material={materials.Afternoon} position={[-28.646, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_7'].geometry} material={materials.Afternoon} position={[-47.096, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_20'].geometry} material={materials.Afternoon} position={[49.611, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_63'].geometry} material={materials.Afternoon} position={[-1.941, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_81'].geometry} material={materials.Afternoon} position={[-57.455, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_114'].geometry} material={materials.Afternoon} position={[-47.096, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_127'].geometry} material={materials.Afternoon} position={[51.642, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_143'].geometry} material={materials.Afternoon} position={[-38.478, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_144'].geometry} material={materials.Afternoon} position={[-33.562, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_8'].geometry} material={materials.Afternoon} position={[-38.959, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_38'].geometry} material={materials.Afternoon} position={[-20.862, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_9'].geometry} material={materials.Afternoon} position={[-32.474, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_11'].geometry} material={materials.Afternoon} position={[-22.265, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_59'].geometry} material={materials.Afternoon} position={[-26.535, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_69'].geometry} material={materials.Afternoon} position={[41.574, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_76'].geometry} material={materials.Afternoon} position={[-91.432, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_86'].geometry} material={materials.Afternoon} position={[-19.529, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_93'].geometry} material={materials.Afternoon} position={[34.112, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_98'].geometry} material={materials.Afternoon} position={[67.417, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_104'].geometry} material={materials.Afternoon} position={[107.962, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_117'].geometry} material={materials.Afternoon} position={[-25.696, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_129'].geometry} material={materials.Afternoon} position={[64.527, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_136'].geometry} material={materials.Afternoon} position={[-93.743, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_155'].geometry} material={materials.Afternoon} position={[40.47, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_10'].geometry} material={materials.Afternoon} position={[-29.029, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_16'].geometry} material={materials.Afternoon} position={[16.026, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_26'].geometry} material={materials.Afternoon} position={[85.563, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_28'].geometry} material={materials.Afternoon} position={[-103.116, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_65'].geometry} material={materials.Afternoon} position={[10.468, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_85'].geometry} material={materials.Afternoon} position={[-29.515, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_115'].geometry} material={materials.Afternoon} position={[-38.959, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_150'].geometry} material={materials.Afternoon} position={[5.611, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_13'].geometry} material={materials.Afternoon} position={[-10.864, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_45'].geometry} material={materials.Afternoon} position={[32.582, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_48'].geometry} material={materials.Afternoon} position={[56.993, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_51'].geometry} material={materials.Afternoon} position={[-95.581, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_60'].geometry} material={materials.Afternoon} position={[-23.089, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_70'].geometry} material={materials.Afternoon} position={[45.019, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_87'].geometry} material={materials.Afternoon} position={[-16.083, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_94'].geometry} material={materials.Afternoon} position={[37.557, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_106'].geometry} material={materials.Afternoon} position={[119.362, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_119'].geometry} material={materials.Afternoon} position={[-14.758, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_146'].geometry} material={materials.Afternoon} position={[-21.153, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_156'].geometry} material={materials.Afternoon} position={[43.916, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_14'].geometry} material={materials.Afternoon} position={[0.382, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_35'].geometry} material={materials.Afternoon} position={[-47.683, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_15'].geometry} material={materials.Afternoon} position={[8.491, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_30'].geometry} material={materials.Afternoon} position={[-90.721, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_47'].geometry} material={materials.Afternoon} position={[49.459, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_50'].geometry} material={materials.Afternoon} position={[-103.116, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_57'].geometry} material={materials.Afternoon} position={[-49.756, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_83'].geometry} material={materials.Afternoon} position={[-45.047, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_102'].geometry} material={materials.Afternoon} position={[94.797, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_122'].geometry} material={materials.Afternoon} position={[10.48, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_130'].geometry} material={materials.Afternoon} position={[67.972, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_139'].geometry} material={materials.Afternoon} position={[-76.223, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_18'].geometry} material={materials.Afternoon} position={[30.284, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_36'].geometry} material={materials.Afternoon} position={[-36.352, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_49'].geometry} material={materials.Afternoon} position={[65.019, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_52'].geometry} material={materials.Afternoon} position={[-87.556, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_68'].geometry} material={materials.Afternoon} position={[30.355, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_84'].geometry} material={materials.Afternoon} position={[-37.512, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_90'].geometry} material={materials.Afternoon} position={[15.177, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_153'].geometry} material={materials.Afternoon} position={[26.031, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_22'].geometry} material={materials.Afternoon} position={[62.482, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_27'].geometry} material={materials.Afternoon} position={[92.327, -13.773, 28.466]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_55'].geometry} material={materials.Afternoon} position={[-63.495, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_32'].geometry} material={materials.Afternoon} position={[-76.688, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_33'].geometry} material={materials.Afternoon} position={[-66.268, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_75'].geometry} material={materials.Afternoon} position={[-102.525, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_40'].geometry} material={materials.Afternoon} position={[-6.885, -13.773, 44.028]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_73'].geometry} material={materials.Afternoon} position={[69.612, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_74'].geometry} material={materials.Afternoon} position={[73.058, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_92'].geometry} material={materials.Afternoon} position={[30.666, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_101'].geometry} material={materials.Afternoon} position={[91.352, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_148'].geometry} material={materials.Afternoon} position={[-7.498, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_53'].geometry} material={materials.Afternoon} position={[-76.338, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_54'].geometry} material={materials.Afternoon} position={[-67.206, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_56'].geometry} material={materials.Afternoon} position={[-56.688, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_138'].geometry} material={materials.Afternoon} position={[-83.155, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_71'].geometry} material={materials.Afternoon} position={[56.265, -13.773, 59.589]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_78'].geometry} material={materials.Afternoon} position={[-82.357, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_80'].geometry} material={materials.Afternoon} position={[-65.48, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_134'].geometry} material={materials.Afternoon} position={[100.913, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_88'].geometry} material={materials.Afternoon} position={[-4.837, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_95'].geometry} material={materials.Afternoon} position={[45.582, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_128'].geometry} material={materials.Afternoon} position={[56.558, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_157'].geometry} material={materials.Afternoon} position={[51.941, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_96'].geometry} material={materials.Afternoon} position={[53.551, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_97'].geometry} material={materials.Afternoon} position={[59.447, -13.773, 75.151]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_124'].geometry} material={materials.Afternoon} position={[26.866, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_131'].geometry} material={materials.Afternoon} position={[78.728, -13.773, 90.712]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_135'].geometry} material={materials.Afternoon} position={[-103.645, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_137'].geometry} material={materials.Afternoon} position={[-90.298, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_149'].geometry} material={materials.Afternoon} position={[-4.053, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_-_Letter_154'].geometry} material={materials.Afternoon} position={[34.028, -13.773, 106.274]} scale={0.311} />
          <mesh geometry={nodes.Box_1.geometry} material={materials['Ancient 1']} position={[10.119, 1.399, 0]} scale={2.13} />
        </group>
        <group position={[10.119, 0, 0]}>
          <mesh geometry={nodes.Box_2.geometry} material={materials['Ancient 2']} position={[-59.907, -6.187, 11.79]} scale={2.13} />
          <mesh geometry={nodes['3D_Text_1_-_w'].geometry} material={materials['Afternoon 1']} position={[-120, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_w_1'].geometry} material={materials['Afternoon 1']} position={[-70.827, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_w_2'].geometry} material={materials['Afternoon 1']} position={[29.04, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_w_3'].geometry} material={materials['Afternoon 1']} position={[-50.278, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_a'].geometry} material={materials['Afternoon 1']} position={[-108.908, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_a_1'].geometry} material={materials['Afternoon 1']} position={[-23.587, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_a_2'].geometry} material={materials['Afternoon 1']} position={[62.742, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_a_3'].geometry} material={materials['Afternoon 1']} position={[-48.129, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_a_4'].geometry} material={materials['Afternoon 1']} position={[-24.908, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_a_5'].geometry} material={materials['Afternoon 1']} position={[-7.388, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_a_6'].geometry} material={materials['Afternoon 1']} position={[40.132, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_t'].geometry} material={materials['Afternoon 1']} position={[-101.373, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_t_1'].geometry} material={materials['Afternoon 1']} position={[-37.327, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_t_2'].geometry} material={materials['Afternoon 1']} position={[16.342, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_t_3'].geometry} material={materials['Afternoon 1']} position={[23.41, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_t_4'].geometry} material={materials['Afternoon 1']} position={[-79.536, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_c'].geometry} material={materials['Afternoon 1']} position={[-95.743, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_c_1'].geometry} material={materials['Afternoon 1']} position={[21.972, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_c_2'].geometry} material={materials['Afternoon 1']} position={[-120.747, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_c_3'].geometry} material={materials['Afternoon 1']} position={[18.166, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_h'].geometry} material={materials['Afternoon 1']} position={[-89.245, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_h_1'].geometry} material={materials['Afternoon 1']} position={[28.471, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_h_2'].geometry} material={materials['Afternoon 1']} position={[6.695, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_i'].geometry} material={materials['Afternoon 1']} position={[-81.219, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_i_1'].geometry} material={materials['Afternoon 1']} position={[-59.735, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_i_2'].geometry} material={materials['Afternoon 1']} position={[-31.36, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_i_3'].geometry} material={materials['Afternoon 1']} position={[36.496, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_i_4'].geometry} material={materials['Afternoon 1']} position={[86.784, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_i_5'].geometry} material={materials['Afternoon 1']} position={[-15.895, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_i_6'].geometry} material={materials['Afternoon 1']} position={[14.721, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_i_7'].geometry} material={materials['Afternoon 1']} position={[42.199, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n'].geometry} material={materials['Afternoon 1']} position={[-77.774, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n_1'].geometry} material={materials['Afternoon 1']} position={[-106.695, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n_2'].geometry} material={materials['Afternoon 1']} position={[-27.915, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n_3'].geometry} material={materials['Afternoon 1']} position={[39.941, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n_4'].geometry} material={materials['Afternoon 1']} position={[70.277, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n_5'].geometry} material={materials['Afternoon 1']} position={[70.79, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n_6'].geometry} material={materials['Afternoon 1']} position={[90.23, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n_7'].geometry} material={materials['Afternoon 1']} position={[-87.561, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_n_8'].geometry} material={materials['Afternoon 1']} position={[-12.45, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_g'].geometry} material={materials['Afternoon 1']} position={[-69.749, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_g_1'].geometry} material={materials['Afternoon 1']} position={[-19.89, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_g_2'].geometry} material={materials['Afternoon 1']} position={[47.966, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_g_3'].geometry} material={materials['Afternoon 1']} position={[-61.014, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_g_4'].geometry} material={materials['Afternoon 1']} position={[78.815, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_f'].geometry} material={materials['Afternoon 1']} position={[-58.559, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_f_1'].geometry} material={materials['Afternoon 1']} position={[18.088, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_f_2'].geometry} material={materials['Afternoon 1']} position={[36.877, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_o'].geometry} material={materials['Afternoon 1']} position={[-53.237, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_o_1'].geometry} material={materials['Afternoon 1']} position={[-45.282, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_o_2'].geometry} material={materials['Afternoon 1']} position={[-95.211, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_o_3'].geometry} material={materials['Afternoon 1']} position={[-114.249, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_o_4'].geometry} material={materials['Afternoon 1']} position={[-101.28, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_o_5'].geometry} material={materials['Afternoon 1']} position={[-68.969, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_o_6'].geometry} material={materials['Afternoon 1']} position={[10.133, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_o_7'].geometry} material={materials['Afternoon 1']} position={[-39.186, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_b'].geometry} material={materials['Afternoon 1']} position={[-31.696, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_l'].geometry} material={materials['Afternoon 1']} position={[-16.052, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_l_1'].geometry} material={materials['Afternoon 1']} position={[-12.607, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_l_2'].geometry} material={materials['Afternoon 1']} position={[-73.906, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_l_3'].geometry} material={materials['Afternoon 1']} position={[45.644, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_'].geometry} material={materials['Afternoon 1']} position={[-9.162, -13.773, 23.579]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-__1'].geometry} material={materials['Afternoon 1']} position={[118.156, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_I'].geometry} material={materials['Afternoon 1']} position={[-121.121, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_I_1'].geometry} material={materials['Afternoon 1']} position={[-57.211, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_e'].geometry} material={materials['Afternoon 1']} position={[-114.188, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_e_1'].geometry} material={materials['Afternoon 1']} position={[8.849, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_e_2'].geometry} material={materials['Afternoon 1']} position={[52.583, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_e_3'].geometry} material={materials['Afternoon 1']} position={[63.297, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_e_4'].geometry} material={materials['Afternoon 1']} position={[98.255, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_e_5'].geometry} material={materials['Afternoon 1']} position={[105.748, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_e_6'].geometry} material={materials['Afternoon 1']} position={[-95.054, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_j'].geometry} material={materials['Afternoon 1']} position={[-98.67, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_y'].geometry} material={materials['Afternoon 1']} position={[-87.256, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_y_1'].geometry} material={materials['Afternoon 1']} position={[-70.46, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_s'].geometry} material={materials['Afternoon 1']} position={[-77.592, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_s_1'].geometry} material={materials['Afternoon 1']} position={[-5.114, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_s_2'].geometry} material={materials['Afternoon 1']} position={[-17.374, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_s_3'].geometry} material={materials['Afternoon 1']} position={[3.368, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_s_4'].geometry} material={materials['Afternoon 1']} position={[66.82, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_m'].geometry} material={materials['Afternoon 1']} position={[-56.29, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_m_1'].geometry} material={materials['Afternoon 1']} position={[-43.825, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_m_2'].geometry} material={materials['Afternoon 1']} position={[-40.595, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_,'].geometry} material={materials['Afternoon 1']} position={[-11.921, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_,_1'].geometry} material={materials['Afternoon 1']} position={[55.935, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_,_2'].geometry} material={materials['Afternoon 1']} position={[-64.018, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_k'].geometry} material={materials['Afternoon 1']} position={[1.65, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_k_1'].geometry} material={materials['Afternoon 1']} position={[-26.315, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_k_2'].geometry} material={materials['Afternoon 1']} position={[24.664, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_d'].geometry} material={materials['Afternoon 1']} position={[78.302, -13.773, 39.141]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_-'].geometry} material={materials['Afternoon 1']} position={[-106.294, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_-_1'].geometry} material={materials['Afternoon 1']} position={[31.863, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_-_2'].geometry} material={materials['Afternoon 1']} position={[49.09, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_p'].geometry} material={materials['Afternoon 1']} position={[-93.325, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_p_1'].geometry} material={materials['Afternoon 1']} position={[-81.994, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_r'].geometry} material={materials['Afternoon 1']} position={[-73.885, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_r_1'].geometry} material={materials['Afternoon 1']} position={[-53.045, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_r_2'].geometry} material={materials['Afternoon 1']} position={[47.667, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_r_3'].geometry} material={materials['Afternoon 1']} position={[113.241, -13.773, 54.702]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_r_4'].geometry} material={materials['Afternoon 1']} position={[-104.885, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_r_5'].geometry} material={materials['Afternoon 1']} position={[-99.97, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_r_6'].geometry} material={materials['Afternoon 1']} position={[-31.231, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_C'].geometry} material={materials['Afternoon 1']} position={[-120.81, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_C_1'].geometry} material={materials['Afternoon 1']} position={[-1.204, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_u'].geometry} material={materials['Afternoon 1']} position={[-112.91, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_A'].geometry} material={materials['Afternoon 1']} position={[54.104, -13.773, 70.264]} scale={0.311} />
          <mesh geometry={nodes['3D_Text_1_-_Apostrophe'].geometry} material={materials['Afternoon 1']} position={[63.235, -13.773, 70.264]} scale={0.311} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/AboutMe.gltf')
