/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 InstructionText.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function InstructionText(props) {
  const { nodes, materials } = useGLTF('/InstructionText.gltf')
  return (
    <group {...props} dispose={null} position={[-4, -2, 38 ]}>
      <group rotation={[-Math.PI/2 , 0, Math.PI/3.2]} scale={0.04}>
        <mesh geometry={nodes['3D_Text_-_H'].geometry} material={materials.Melody} position={[-132.59, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_o'].geometry} material={materials.Melody} position={[-120.5, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_o_1'].geometry} material={materials.Melody} position={[-33.828, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_o_2'].geometry} material={materials.Melody} position={[-9.919, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_o_3'].geometry} material={materials.Melody} position={[62.081, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_o_4'].geometry} material={materials.Melody} position={[96.315, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_l'].geometry} material={materials.Melody} position={[-110.99, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_d'].geometry} material={materials.Melody} position={[-107.458, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_s'].geometry} material={materials.Melody} position={[-92.515, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_p'].geometry} material={materials.Melody} position={[-83.005, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_a'].geometry} material={materials.Melody} position={[-73.496, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_c'].geometry} material={materials.Melody} position={[-63.987, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_c_1'].geometry} material={materials.Melody} position={[-18.885, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_e'].geometry} material={materials.Melody} position={[-55.021, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_e_1'].geometry} material={materials.Melody} position={[37.9, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_e_2'].geometry} material={materials.Melody} position={[131.093, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_t'].geometry} material={materials.Melody} position={[-40.077, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_t_1'].geometry} material={materials.Melody} position={[9.1, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_n'].geometry} material={materials.Melody} position={[-0.409, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_n_1'].geometry} material={materials.Melody} position={[18.881, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_n_2'].geometry} material={materials.Melody} position={[121.583, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_i'].geometry} material={materials.Melody} position={[15.349, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_u'].geometry} material={materials.Melody} position={[28.391, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_u_1'].geometry} material={materials.Melody} position={[71.591, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_u_2'].geometry} material={materials.Melody} position={[105.825, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_y'].geometry} material={materials.Melody} position={[52.844, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_y_1'].geometry} material={materials.Melody} position={[140.602, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_r'].geometry} material={materials.Melody} position={[81.1, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_r_1'].geometry} material={materials.Melody} position={[115.334, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_j'].geometry} material={materials.Melody} position={[92.783, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-_'].geometry} material={materials.Melody} position={[149.84, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-__1'].geometry} material={materials.Melody} position={[153.915, 0, 79.231]} scale={0.302} />
        <mesh geometry={nodes['3D_Text_-__2'].geometry} material={materials.Melody} position={[157.991, 0, 79.231]} scale={0.302} />
      </group>
    </group>
  )
}

useGLTF.preload('/InstructionText.gltf')

export default InstructionText;
