/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 planet.gltf --transform 
Files: planet.gltf [6.06KB] > /Users/nikvijay/Desktop/git/space-world/personal-website/public/planet-transformed.glb [60.49KB] (-898%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet(props) {
  const { nodes, materials } = useGLTF('/planet-transformed.glb')
  const relativePosition = [-5, -6.5, 25]
  return (
    <group onClick={props.displaySpaceBase} scale={1} {...props} dispose={null}>
      <mesh geometry={nodes._switchable.geometry}  material={materials._switchable} position={[-5, 1, 18.5]} scale={0.2} />
      <mesh geometry={nodes.Ring_1.geometry} material={materials['Ring 1']} position={[-4, 2.9, 17]} scale={0.15} />
      <mesh geometry={nodes.Ring_2.geometry} material={materials['Ring 2']} position={[-4, 2.9, 17]} scale={0.15} />
      <mesh geometry={nodes.Ring_3.geometry} material={materials['Ring 3']} position={[-4, 2.9, 17]} scale={0.15} />
    </group>
  )
}

useGLTF.preload('/planet-transformed.glb')
