/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rocket.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rocket.gltf')
  return (
    <group {...props} dispose={null} scale={10}>
      <group position={[-0.018, -0.029, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['Box_-_baked'].geometry} material={materials.Milton} position={[47.234, -47.364, 42.333]} rotation={[0.211, 0.124, 0.524]} scale={1.011} />
        <mesh geometry={nodes['Box_-_baked_1'].geometry} material={materials.Milton} position={[42.691, 46.718, 42.333]} rotation={[-0.214, 0.118, 2.644]} scale={1.011} />
        <mesh geometry={nodes['Box_-_baked_2'].geometry} material={materials.Milton} position={[-36.515, -4.258, 42.333]} rotation={[0.003, -0.244, -1.557]} scale={1.011} />
        <mesh geometry={nodes.Torus.geometry} material={materials.Saturn} position={[74.789, -1.691, 115.903]} rotation={[0.164, 1.276, -0.204]} scale={0.918} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Alley} position={[17.999, -1.635, 38.371]} rotation={[-Math.PI, 0.003, -Math.PI]} scale={0.669} />
        <mesh geometry={nodes.Cone.geometry} material={materials.Retro} position={[17.803, -1.635, 144.924]} scale={1.208} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Urban Charm']} position={[17.803, -1.635, 15.95]} scale={1.11} />
      </group>
    </group>
  )
}

useGLTF.preload('/rocket.gltf')
