/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 textBox.gltf --transform 
Files: textBox.gltf [2.81KB] > /Users/nikvijay/Desktop/git/space-world/personal-website/public/textBox-transformed.glb [7.29KB] (-159%)
*/

import { useGLTF } from '@react-three/drei'
import { Text3D } from '@react-three/drei';

export function TextBox(props) {
  const { nodes, materials } = useGLTF('/textBox-transformed.glb')
  const lines = "Hi! My name is Nikhil Vijayvergiya \nand welcome to my universe! I am a \nsoftware engineer with most of my \nexperience from improving and scaling \nbackend systems. I enjoy learning about \nany new skills or new technologies \nacross the stack. \n\nCurrently, I am studying to get my \nBachelors degree in CS at the Georgia \nInstitute of Technology. Outside of school \nand work, some of my hobbies include \ncooking, drawing, and swimming."
  return (
    <>
    <group position={[-6, 4.5, 25.9]} {...props} dispose={null}>
      <mesh geometry={nodes.Cone.geometry} material={materials.Malibu} position={[-0.044, 0.096, -0.001]} rotation={[-0.52, 0, Math.PI/2]} scale={0.05} />
    </group>
    {
      lines.split('\n').map((line, index) => {
        return (
          <Text3D
            key={index}
            scale={[0.15, 0.15, 0.15]}
            position={[-5.7, 4.3 - index * 0.3, 25.8]}
            rotation={[0, Math.PI/2, 0]}
            font="./roboto_black.json"
            
          >
            {line}
            <meshToonMaterial color={"#000000"} />
          </Text3D>
        )
      })  
    }
    </>
  )
}

useGLTF.preload('/textBox-transformed.glb')
